# Graph89 Remastered - TI graphing calculator emulator for iPhone
# Copyright (C) 2026 JH. GNU General Public License version 3 or later (see LICENSE).
#
# Writes ios/core-targets.yml (included by ios/project.yml): one static library target per native module of the
# Android build (app/src/main/jni/**/Android.mk), with the same sources, include paths and defines, so the iPhone app
# builds the emulators exactly as the Android app does. Defines with string values go into a prefix header per module
# (ios/Graph89Core/prefix), which avoids build-setting quoting. Run it again after changing an Android.mk:
#     python3 ios/scripts/gen_core_targets.py
import os
import re
import sys

IOS = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), '..'))
JNI = os.path.normpath(os.path.join(IOS, '..', 'app', 'src', 'main', 'jni'))

# The modules Application.mk builds (APP_MODULES) -> Xcode target name. glib's gmodule, gthread and gobject
# makefiles have no sources in this tree and are not built.
TARGETS = {
    'wrapper': 'G89Wrapper',
    'tilem-2.0': 'G89TilEm',
    'tiemu-3.03': 'G89TiEmu',
    'ticalcs2-1.1.7': 'G89TiCalcs',
    'tifiles2-1.1.5': 'G89TiFiles',
    'ticables2-1.3.3': 'G89TiCables',
    'ticonv-1.1.3': 'G89TiConv',
    'glib-2.0': 'G89GLib',
}

# files of the Android build that the iPhone app replaces (the JNI layer: ios/Graph89Core/graph89.c instead)
EXCLUDED = {'wrapper/wrappercommonjni.c', 'wrapper/tiemuwrapperjni.c', 'wrapper/tilemwrapperjni.c'}

# extra sources per module (paths relative to ios/)
EXTRA = {'wrapper': ['Graph89Core/graph89.c']}

# include paths searched before the module's own (ios/ relative): the Android log shim and the C API header
SHIM = ['Graph89Core/shim', 'Graph89Core/include']


def parse():
    mods = {}
    for root, _, files in os.walk(JNI):
        if 'Android.mk' not in files:
            continue
        mk = os.path.join(root, 'Android.mk')
        txt = open(mk, encoding='utf-8', errors='replace').read().replace('\r\n', '\n')
        txt = re.sub(r'\\[ \t]*\n', ' ', txt)
        txt = '\n'.join(l for l in txt.split('\n') if not l.strip().startswith('#'))
        local = os.path.relpath(root, JNI).replace(os.sep, '/')
        tops = {'LOCAL_PATH': local}
        for block in re.split(r'include \$\(CLEAR_VARS\)', txt):
            for name, value in re.findall(r'^\s*(\w+_TOP)\s*:?=\s*(\S+)\s*$', block, re.M):
                tops[name] = value
            m = re.search(r'LOCAL_MODULE\s*:?=\s*(\S+)', block)
            if not m:
                continue
            files = []
            for s in re.findall(r'LOCAL_SRC_FILES\s*[:+]?=\s*([^\n]*)', block):
                files += s.split()
            cflags = ' '.join(re.findall(r'LOCAL_CFLAGS\s*[:+]?=\s*([^\n]*)', block)).split()
            mods[m.group(1)] = {'dir': local, 'files': files, 'cflags': cflags, 'tops': dict(tops)}
    return mods


def resolve(path, tops):
    """$(X_TOP)/a/b with the makefile's variables -> a path relative to jni/."""
    for _ in range(5):
        path = re.sub(r'\$\((\w+)\)', lambda m: tops.get(m.group(1), ''), path)
    return os.path.normpath(path).replace(os.sep, '/')


def main():
    mods = parse()
    missing = [m for m in TARGETS if m not in mods]
    if missing:
        sys.exit(f'modules not found in the Android build: {missing}')
    os.makedirs(os.path.join(IOS, 'Graph89Core', 'prefix'), exist_ok=True)
    out = ['# Generated by ios/scripts/gen_core_targets.py from the Android build: do not edit by hand.', 'targets:']
    for module, target in TARGETS.items():
        m = mods[module]
        tops = m['tops']
        includes, defines, prefix, undefines = [], [], [], []
        for f in m['cflags']:
            if f.startswith('-I'):
                includes.append('$(SRCROOT)/../app/src/main/jni/' + resolve(f[2:], tops))
            elif f.startswith('-D'):
                d = f[2:]
                if '"' in d or '$(' in d:
                    name, _, value = d.partition('=')
                    value = re.sub(r'\$\(\w+\)', '', value).replace('\\"', '"')
                    prefix.append(f'#define {name} {value}')
                else:
                    defines.append(d)
            elif f.startswith('-U'):
                undefines.append(f[2:])
        prefix_file = f'Graph89Core/prefix/{target}.h'
        with open(os.path.join(IOS, prefix_file), 'w', newline='\n') as h:
            h.write(f'/* Generated by ios/scripts/gen_core_targets.py: the string defines of {module}\'s Android.mk. */\n')
            for u in undefines:
                h.write(f'#undef {u}\n')
            h.write('\n'.join(prefix) + ('\n' if prefix else ''))
        sources = []
        for f in m['files']:
            rel = resolve(m['dir'] + '/' + f, tops)
            if rel in EXCLUDED:
                continue
            sources.append('../app/src/main/jni/' + rel)
        sources += EXTRA.get(module, [])
        out.append(f'  {target}:')
        out.append('    type: library.static')
        out.append('    platform: iOS')
        out.append('    sources:')
        for s in sources:
            out.append(f'      - path: {s}')
        out.append('    settings:')
        out.append('      base:')
        out.append('        HEADER_SEARCH_PATHS:')
        for i in ['$(SRCROOT)/' + s for s in SHIM] + includes:
            out.append(f'          - "{i}"')
        out.append('        GCC_PREPROCESSOR_DEFINITIONS:')
        out.append('          - "$(inherited)"')
        for d in defines:
            out.append(f'          - "{d}"')
        out.append(f'        GCC_PREFIX_HEADER: {prefix_file}')
        out.append('        GCC_PRECOMPILE_PREFIX_HEADER: NO')
        out.append('        OTHER_CFLAGS: $(inherited) $(G89_CORE_CFLAGS)')
        out.append('        GCC_OPTIMIZATION_LEVEL: 3')
        out.append('        GCC_C_LANGUAGE_STANDARD: gnu17')
        out.append('        GCC_WARN_INHIBIT_ALL_WARNINGS: YES')
        out.append('        CLANG_ENABLE_MODULES: NO')
        out.append('        SKIP_INSTALL: YES')
    with open(os.path.join(IOS, 'core-targets.yml'), 'w', newline='\n') as y:
        y.write('\n'.join(out) + '\n')
    print('wrote ios/core-targets.yml:', ', '.join(f'{t} ({len(mods[m]["files"])} files)' for m, t in TARGETS.items()))


if __name__ == '__main__':
    main()
